apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: NodePort
  selector:
    app: django-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
      # nodePort: 32080   # optional: uncomment if you want a fixed port
