# Generated by Django 5.2.6 on 2025-10-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_add_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['movie_title']},
        ),
        migrations.AlterField(
            model_name='video',
            name='movie_genre',
            field=models.CharField(choices=[('COMEDY', 'Comedy'), ('ROMANCE', 'Romance'), ('ACTION', 'Action'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('SCIFI', 'Sci-Fi'), ('ANIMATION', 'Animation'), ('THRILLER', 'Thriller'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='MovieGenre'),
        ),
    ]
